name: CI (non-release)
on:
  push:
  pull_request:

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yaml
    with:
      mode: snapshot
  post-build:
    needs:
      - build-and-test
    uses: ./.github/workflows/post-build.yaml
